version: '3'

services:
  web:
    build: .
    command: gunicorn -w 2 invent.wsgi:application --bind 0.0.0.0:8000
    volumes:
    - .:/app

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 8000:8000
    depends_on:
      - web

volumes:
  static_volume: